function(EnableWarnings target)
    if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        target_compile_options(${target} PRIVATE /WX)
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        #target_compile_options(${target} PRIVATE -Wall -Wextra -Werror -Wconversion -pedantic-errors)
    endif()
endfunction()
